import { useState } from "react";
import "./DonateFood.css";
import { getFoodImage } from "../utils/foodImages";

export default function DonateFood() {
  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const [foodName, setFoodName] = useState(""); const [quantity, setQuantity] = useState(""); const [location, setLocation] = useState(""); const [expiryTime, setExpiryTime] = useState(""); const [description, setDescription] = useState(""); const [loading, setLoading] = useState(false);
  const preview = foodName ? getFoodImage(foodName) : "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85";
  const handleDonate = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); try { const response = await fetch("http://127.0.0.1:5000/api/food/donate", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({food_name:foodName,quantity,location,expiry_time:expiryTime,description,food_image:getFoodImage(foodName),donor_name:user.full_name,donor_email:user.email}) }); const data = await response.json(); if(data.success){ alert("🎉 Food Donated Successfully! Your donation is now waiting for NGO acceptance."); setFoodName("");setQuantity("");setLocation("");setExpiryTime("");setDescription(""); } else alert(data.message); } catch { alert("Server Error"); } setLoading(false); };
  return <div className="donate-page"><div className="donate-card"><div className="donate-visual"><img src={preview} alt="Food preview"/><span>LIVE FOOD PREVIEW</span></div><div className="donate-form-wrap"><span className="donate-kicker">FOODBRIDGE AI · DONOR</span><h1 className="donate-title">Donate good food, not waste.</h1><p className="subtitle">Add the details once. FoodBridge takes care of NGO matching, QR tracking and delivery updates.</p><div className="location-box"><h4>📍 Donor Information</h4><p><b>Name:</b> {user.full_name}</p><p><b>Email:</b> {user.email}</p></div><form onSubmit={handleDonate}><div className="form-grid"><div className="form-group"><label>Food Name</label><input type="text" placeholder="Biryani, Idly, Meals..." value={foodName} onChange={(e)=>setFoodName(e.target.value)} required/></div><div className="form-group"><label>Quantity</label><input type="text" placeholder="50 meals" value={quantity} onChange={(e)=>setQuantity(e.target.value)} required/></div><div className="form-group full"><label>Pickup Location</label><input type="text" placeholder="Complete pickup address" value={location} onChange={(e)=>setLocation(e.target.value)} required/></div><div className="form-group"><label>Expiry Time</label><input type="datetime-local" value={expiryTime} onChange={(e)=>setExpiryTime(e.target.value)} required/></div><div className="form-group"><label>Description</label><input type="text" placeholder="Packaging, freshness, notes" value={description} onChange={(e)=>setDescription(e.target.value)}/></div></div><button className="donate-btn" disabled={loading}>{loading ? "Creating donation..." : "🍱 Donate Food"}</button></form></div></div></div>;
}
